import { buildDashboardState } from "@/features/dashboard/model";
import type { DashboardSearchFilters } from "@/features/dashboard/search-params";
import type { SavedRecipe } from "@/server/repositories/recipes";
import type { WeeklyPlan } from "@/server/repositories/weekly-plan";
import type { UserPreferences } from "@/server/repositories/user-preferences";

export const veteranPreviewPreferences: UserPreferences = {
  id: "preview-veteran-user",
  age: 34,
  sex: "male",
  heightUnit: "imperial",
  heightFeet: 5,
  heightInches: 11,
  heightCentimeters: null,
  initialWeight: 188,
  weightUnit: "lb",
  activityPerWeek: "5+",
  calorieTarget: 2550,
  mealsPerDay: "4",
  likedFoodTags: ["High protein", "Rice bowls", "One-pan"],
  likedFoodNotes: "Needs a lunch rotation that survives busy work weeks.",
  dislikedFoods: "Mushrooms",
  dietaryRestrictions: "None",
  cookDays: ["sunday", "wednesday"],
  onboardingCompletedAt: "2026-03-14T10:00:00.000Z",
  updatedAt: "2026-04-20T10:00:00.000Z",
};

export const veteranPreviewRecipes: SavedRecipe[] = [
  {
    id: "preview-chicken-yogurt-bowls",
    title: "Harissa Chicken Yogurt Bowls",
    sourceUrl: "https://example.com/harissa-chicken-yogurt-bowls",
    sourceLabel: null,
    notes: null,
    primaryProtein: "Chicken",
    cuisine: "Mediterranean",
    totalCalories: 2360,
    caloriesPerServing: 590,
    proteinGrams: 47,
    carbGrams: 49,
    fatGrams: 18,
    servings: 4,
    prepMinutes: 40,
    tags: ["High protein", "Meal prep", "Lunch"],
    ingredients: [
      "2 lb chicken thighs",
      "Greek yogurt",
      "Basmati rice",
      "Cucumber",
      "Cherry tomatoes",
      "Harissa paste",
    ],
    steps: [
      "Marinate the chicken with harissa and roast until browned.",
      "Cook the rice and mix a quick yogurt sauce.",
      "Build each bowl with rice, vegetables, chicken, and sauce.",
    ],
    favorite: true,
    plannedThisWeek: true,
    createdAt: "2026-04-19T09:00:00.000Z",
    updatedAt: "2026-04-19T09:00:00.000Z",
  },
  {
    id: "preview-beef-kimchi-rice",
    title: "Beef Kimchi Rice Skillet",
    sourceUrl: "https://example.com/beef-kimchi-rice-skillet",
    sourceLabel: null,
    notes: null,
    primaryProtein: "Beef",
    cuisine: "Asian",
    totalCalories: 2520,
    caloriesPerServing: 630,
    proteinGrams: 43,
    carbGrams: 56,
    fatGrams: 20,
    servings: 4,
    prepMinutes: 35,
    tags: ["One-pan", "Dinner", "Comfort"],
    ingredients: [
      "90% lean ground beef",
      "Cooked jasmine rice",
      "Kimchi",
      "Scallions",
      "Sesame oil",
    ],
    steps: [
      "Brown the beef and season it aggressively.",
      "Stir in kimchi and rice until everything is hot.",
      "Finish with scallions and sesame oil before portioning.",
    ],
    favorite: true,
    plannedThisWeek: false,
    createdAt: "2026-04-17T09:00:00.000Z",
    updatedAt: "2026-04-17T09:00:00.000Z",
  },
  {
    id: "preview-salmon-herb-potatoes",
    title: "Sheet-Pan Salmon and Herb Potatoes",
    sourceUrl: "https://example.com/salmon-herb-potatoes",
    sourceLabel: null,
    notes: null,
    primaryProtein: "Fish",
    cuisine: "American",
    totalCalories: 2280,
    caloriesPerServing: 570,
    proteinGrams: 41,
    carbGrams: 38,
    fatGrams: 24,
    servings: 4,
    prepMinutes: 32,
    tags: ["Sheet pan", "Dinner", "Low friction"],
    ingredients: [
      "Salmon fillets",
      "Baby potatoes",
      "Green beans",
      "Lemon",
      "Fresh dill",
    ],
    steps: [
      "Roast the potatoes until almost tender.",
      "Add salmon and green beans to the same pan.",
      "Finish with lemon and dill before portioning.",
    ],
    favorite: false,
    plannedThisWeek: true,
    createdAt: "2026-04-16T09:00:00.000Z",
    updatedAt: "2026-04-16T09:00:00.000Z",
  },
  {
    id: "preview-chicken-burrito-bake",
    title: "Chicken Burrito Tray Bake",
    sourceUrl: "https://example.com/chicken-burrito-tray-bake",
    sourceLabel: null,
    notes: null,
    primaryProtein: "Chicken",
    cuisine: "Mexican",
    totalCalories: 2680,
    caloriesPerServing: 670,
    proteinGrams: 45,
    carbGrams: 61,
    fatGrams: 18,
    servings: 4,
    prepMinutes: 45,
    tags: ["Batch cook", "Lunch", "Crowd pleaser"],
    ingredients: [
      "Chicken breast",
      "Black beans",
      "Rice",
      "Salsa",
      "Bell peppers",
      "Cheddar cheese",
    ],
    steps: [
      "Bake seasoned chicken with peppers until cooked through.",
      "Fold in rice, beans, salsa, and cheese.",
      "Return to the oven briefly and divide into containers.",
    ],
    favorite: true,
    plannedThisWeek: false,
    createdAt: "2026-04-15T09:00:00.000Z",
    updatedAt: "2026-04-15T09:00:00.000Z",
  },
  {
    id: "preview-turkey-pesto-orzo",
    title: "Turkey Pesto Orzo Boxes",
    sourceUrl: "https://example.com/turkey-pesto-orzo",
    sourceLabel: null,
    notes: null,
    primaryProtein: "Turkey",
    cuisine: "Italian",
    totalCalories: 2160,
    caloriesPerServing: 540,
    proteinGrams: 39,
    carbGrams: 52,
    fatGrams: 16,
    servings: 4,
    prepMinutes: 28,
    tags: ["Quick", "Lunch", "Cold friendly"],
    ingredients: [
      "Ground turkey",
      "Orzo",
      "Spinach",
      "Pesto",
      "Parmesan",
    ],
    steps: [
      "Cook the turkey and season lightly.",
      "Boil the orzo and toss with pesto and spinach.",
      "Combine everything and finish with parmesan.",
    ],
    favorite: false,
    plannedThisWeek: false,
    createdAt: "2026-04-12T09:00:00.000Z",
    updatedAt: "2026-04-12T09:00:00.000Z",
  },
  {
    id: "preview-tofu-peanut-noodles",
    title: "Crispy Tofu Peanut Noodles",
    sourceUrl: "https://example.com/tofu-peanut-noodles",
    sourceLabel: null,
    notes: null,
    primaryProtein: "Tofu",
    cuisine: "Asian",
    totalCalories: 2440,
    caloriesPerServing: 610,
    proteinGrams: 31,
    carbGrams: 63,
    fatGrams: 22,
    servings: 4,
    prepMinutes: 42,
    tags: ["Meatless", "Dinner", "Saucy"],
    ingredients: [
      "Extra-firm tofu",
      "Rice noodles",
      "Peanut butter",
      "Soy sauce",
      "Carrots",
      "Cabbage",
    ],
    steps: [
      "Bake the tofu until crisp.",
      "Whisk a peanut sauce and cook the noodles.",
      "Toss everything together with the vegetables.",
    ],
    favorite: false,
    plannedThisWeek: false,
    createdAt: "2026-04-10T09:00:00.000Z",
    updatedAt: "2026-04-10T09:00:00.000Z",
  },
  {
    id: "preview-pork-green-salsa",
    title: "Pork Tenderloin Green Salsa Bowls",
    sourceUrl: "https://example.com/pork-green-salsa-bowls",
    sourceLabel: null,
    notes: null,
    primaryProtein: "Pork",
    cuisine: "Mexican",
    totalCalories: 2400,
    caloriesPerServing: 600,
    proteinGrams: 44,
    carbGrams: 48,
    fatGrams: 19,
    servings: 4,
    prepMinutes: 38,
    tags: ["Rice bowls", "Dinner", "Balanced"],
    ingredients: [
      "Pork tenderloin",
      "Rice",
      "Tomatillo salsa",
      "Corn",
      "Avocado",
    ],
    steps: [
      "Roast the pork until just cooked.",
      "Warm the rice and corn with salsa.",
      "Slice the pork and portion with avocado.",
    ],
    favorite: false,
    plannedThisWeek: false,
    createdAt: "2026-04-08T09:00:00.000Z",
    updatedAt: "2026-04-08T09:00:00.000Z",
  },
  {
    id: "preview-chicken-ginger-meatballs",
    title: "Chicken Ginger Meatball Boxes",
    sourceUrl: "https://example.com/chicken-ginger-meatballs",
    sourceLabel: null,
    notes: null,
    primaryProtein: "Chicken",
    cuisine: "Asian",
    totalCalories: 2480,
    caloriesPerServing: 620,
    proteinGrams: 46,
    carbGrams: 51,
    fatGrams: 18,
    servings: 4,
    prepMinutes: 44,
    tags: ["Freezer", "Lunch", "High protein"],
    ingredients: [
      "Ground chicken",
      "Panko",
      "Ginger",
      "Rice",
      "Snap peas",
    ],
    steps: [
      "Bake the ginger chicken meatballs.",
      "Steam the snap peas and cook the rice.",
      "Pack the boxes with a quick soy glaze.",
    ],
    favorite: true,
    plannedThisWeek: false,
    createdAt: "2026-04-07T09:00:00.000Z",
    updatedAt: "2026-04-07T09:00:00.000Z",
  },
  {
    id: "preview-beans-chipotle-chili",
    title: "Chipotle Turkey and Bean Chili",
    sourceUrl: "https://example.com/chipotle-turkey-bean-chili",
    sourceLabel: null,
    notes: null,
    primaryProtein: "Turkey",
    cuisine: "American",
    totalCalories: 2300,
    caloriesPerServing: 575,
    proteinGrams: 42,
    carbGrams: 44,
    fatGrams: 17,
    servings: 4,
    prepMinutes: 55,
    tags: ["Batch cook", "Freezer", "Comfort"],
    ingredients: [
      "Ground turkey",
      "Kidney beans",
      "Tomatoes",
      "Onion",
      "Chipotle peppers",
    ],
    steps: [
      "Brown the turkey with onion and spices.",
      "Simmer with tomatoes and beans until thick.",
      "Cool slightly and portion for the week or freezer.",
    ],
    favorite: true,
    plannedThisWeek: true,
    createdAt: "2026-04-05T09:00:00.000Z",
    updatedAt: "2026-04-05T09:00:00.000Z",
  },
];

export const veteranPreviewWeeklyPlan: WeeklyPlan = {
  mealCount: 3,
  updatedAt: "2026-04-20T10:00:00.000Z",
  slots: [
    {
      slotIndex: 0,
      recipeId: "preview-chicken-yogurt-bowls",
      updatedAt: "2026-04-20T10:00:00.000Z",
    },
    {
      slotIndex: 1,
      recipeId: "preview-salmon-herb-potatoes",
      updatedAt: "2026-04-20T10:00:00.000Z",
    },
    {
      slotIndex: 2,
      recipeId: "preview-beans-chipotle-chili",
      updatedAt: "2026-04-20T10:00:00.000Z",
    },
  ],
};

export function getVeteranPreviewDashboardState(filters: DashboardSearchFilters) {
  return buildDashboardState(
    veteranPreviewRecipes,
    veteranPreviewPreferences,
    filters,
    veteranPreviewWeeklyPlan,
  );
}

export function getVeteranPreviewRecipeById(id: string) {
  return veteranPreviewRecipes.find((recipe) => recipe.id === id) ?? null;
}
